# Generated by Django 6.0.3 on 2026-03-22 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('action', 'Action'), ('crime', 'Crime'), ('family', 'Family'), ('horror', 'Horror'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('thriller', 'Thriller'), ('sci_fi', 'Sci-Fi'), ('romance', 'Romance'), ('animation', 'Animation')], max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(default='🎬', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('cast', models.TextField(help_text='Comma-separated cast names')),
                ('director', models.CharField(max_length=100)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('release_date', models.DateField()),
                ('language', models.CharField(choices=[('english', 'English'), ('hindi', 'Hindi'), ('telugu', 'Telugu'), ('tamil', 'Tamil'), ('malayalam', 'Malayalam')], default='english', max_length=20)),
                ('rating', models.CharField(choices=[('U', 'U - Universal'), ('UA', 'UA - Universal Adult'), ('A', 'A - Adult')], default='UA', max_length=5)),
                ('imdb_score', models.DecimalField(decimal_places=1, default=7.0, max_digits=3)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('poster_url', models.URLField(blank=True, help_text='External poster URL if no upload')),
                ('trailer_url', models.URLField(blank=True, help_text='YouTube embed URL')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tags', models.CharField(blank=True, help_text='Keywords for AI recommendations', max_length=500)),
                ('categories', models.ManyToManyField(related_name='movies', to='movies.category')),
            ],
            options={
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('total_rows', models.PositiveIntegerField(default=8)),
                ('seats_per_row', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('theatre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='movies.theatre')),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_date', models.DateField()),
                ('show_time', models.TimeField()),
                ('ticket_price', models.DecimalField(decimal_places=2, default=200.0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='movies.movie')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='movies.screen')),
            ],
            options={
                'ordering': ['show_date', 'show_time'],
                'unique_together': {('screen', 'show_date', 'show_time')},
            },
        ),
    ]
